### ISSUE TITLE
API Queries

### ISSUE THREAD

**Issue by CollinSchneider** [benbli/projectthree#2]
Attempting to add a query string to our get request to our API that only returns textbooks that belong to users that go to the same college that the current user goes to (that way they only see textbooks that are on their campus). Not sure how to make that request, I've tried adding to the end our api '/api/users?q=college:NYU' and variations of it but cannot retrieve it correctly.
Also have a question regarding the patch request in our routes, where we want to update a single textbook, so the patch route would be '/users/:id/textbooks/:id', however I'm unsure how to grab each textbook...

**Comment by ajhofferber** [comment]
RAFA TO THE RESCUE.
